import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QIcon

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1080, 1920)
        self.calendar_widget = QtWidgets.QCalendarWidget(Dialog)
        self.calendar_widget.setGeometry(QtCore.QRect(0, 760, 1080, 750))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.calendar_widget.setFont(font)
        self.calendar_widget.setAutoFillBackground(True)
        self.calendar_widget.setGridVisible(False)
        self.calendar_widget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendar_widget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar_widget.setNavigationBarVisible(True)
        self.calendar_widget.setDateEditEnabled(True)
        self.calendar_widget.setObjectName("calendar_widget")
        self.weather_widget = QtWidgets.QWidget(Dialog)
        self.weather_widget.setGeometry(QtCore.QRect(820, 530, 250, 220))
        self.weather_widget.setObjectName("weather_widget")
        self.weather_forecast_min_label_1 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_min_label_1.setGeometry(QtCore.QRect(70, 200, 25, 16))
        self.weather_forecast_min_label_1.setObjectName("weather_forecast_min_label_1")
        self.weather_forecast_max_label_1 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_max_label_1.setGeometry(QtCore.QRect(95, 200, 25, 16))
        self.weather_forecast_max_label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weather_forecast_max_label_1.setObjectName("weather_forecast_max_label_1")
        self.rainprobability_label_1 = QtWidgets.QLabel(self.weather_widget)
        self.rainprobability_label_1.setGeometry(QtCore.QRect(85, 180, 35, 20))
        self.rainprobability_label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rainprobability_label_1.setObjectName("rainprobability_label_1")
        self.rainprobability_graphic_1 = QtWidgets.QGraphicsView(self.weather_widget)
        self.rainprobability_graphic_1.setGeometry(QtCore.QRect(70, 180, 15, 20))
        self.rainprobability_graphic_1.setObjectName("rainprobability_graphic_1")
        self.weather_forecast_day_label_1 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_day_label_1.setGeometry(QtCore.QRect(70, 110, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weather_forecast_day_label_1.setFont(font)
        self.weather_forecast_day_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_forecast_day_label_1.setObjectName("weather_forecast_day_label_1")
        self.weather_forecast_graphic_1 = QtWidgets.QGraphicsView(self.weather_widget)
        self.weather_forecast_graphic_1.setGeometry(QtCore.QRect(70, 130, 50, 50))
        self.weather_forecast_graphic_1.setObjectName("weather_forecast_graphic_1")
        self.weather_forecast_max_label_2 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_max_label_2.setGeometry(QtCore.QRect(155, 200, 25, 16))
        self.weather_forecast_max_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weather_forecast_max_label_2.setObjectName("weather_forecast_max_label_2")
        self.rainprobability_label_2 = QtWidgets.QLabel(self.weather_widget)
        self.rainprobability_label_2.setGeometry(QtCore.QRect(145, 180, 35, 20))
        self.rainprobability_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rainprobability_label_2.setObjectName("rainprobability_label_2")
        self.weather_forecast_min_label_2 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_min_label_2.setGeometry(QtCore.QRect(130, 200, 25, 16))
        self.weather_forecast_min_label_2.setObjectName("weather_forecast_min_label_2")
        self.rainprobability_graphic_2 = QtWidgets.QGraphicsView(self.weather_widget)
        self.rainprobability_graphic_2.setGeometry(QtCore.QRect(130, 180, 15, 20))
        self.rainprobability_graphic_2.setObjectName("rainprobability_graphic_2")
        self.weather_forecast_day_label_2 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_day_label_2.setGeometry(QtCore.QRect(130, 110, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weather_forecast_day_label_2.setFont(font)
        self.weather_forecast_day_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_forecast_day_label_2.setObjectName("weather_forecast_day_label_2")
        self.weather_forecast_graphic_2 = QtWidgets.QGraphicsView(self.weather_widget)
        self.weather_forecast_graphic_2.setGeometry(QtCore.QRect(130, 130, 50, 50))
        self.weather_forecast_graphic_2.setObjectName("weather_forecast_graphic_2")
        self.weather_forecast_graphic_3 = QtWidgets.QGraphicsView(self.weather_widget)
        self.weather_forecast_graphic_3.setGeometry(QtCore.QRect(190, 130, 50, 50))
        self.weather_forecast_graphic_3.setObjectName("weather_forecast_graphic_3")
        self.weather_forecast_day_label_3 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_day_label_3.setGeometry(QtCore.QRect(190, 110, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weather_forecast_day_label_3.setFont(font)
        self.weather_forecast_day_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_forecast_day_label_3.setObjectName("weather_forecast_day_label_3")
        self.weather_forecast_min_label_3 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_min_label_3.setGeometry(QtCore.QRect(190, 200, 25, 16))
        self.weather_forecast_min_label_3.setObjectName("weather_forecast_min_label_3")
        self.weather_forecast_max_label_3 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_max_label_3.setGeometry(QtCore.QRect(215, 200, 25, 16))
        self.weather_forecast_max_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weather_forecast_max_label_3.setObjectName("weather_forecast_max_label_3")
        self.rainprobability_label_3 = QtWidgets.QLabel(self.weather_widget)
        self.rainprobability_label_3.setGeometry(QtCore.QRect(205, 180, 35, 20))
        self.rainprobability_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rainprobability_label_3.setObjectName("rainprobability_label_3")
        self.rainprobability_graphic_3 = QtWidgets.QGraphicsView(self.weather_widget)
        self.rainprobability_graphic_3.setGeometry(QtCore.QRect(190, 180, 15, 20))
        self.rainprobability_graphic_3.setObjectName("rainprobability_graphic_3")
        self.weather_act_graphic = QtWidgets.QGraphicsView(self.weather_widget)
        self.weather_act_graphic.setGeometry(QtCore.QRect(75, 10, 75, 75))
        self.weather_act_graphic.setObjectName("weather_act_graphic")
        self.weather_feel_label = QtWidgets.QLabel(self.weather_widget)
        self.weather_feel_label.setGeometry(QtCore.QRect(130, 85, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weather_feel_label.setFont(font)
        self.weather_feel_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weather_feel_label.setObjectName("weather_feel_label")
        self.weather_act_label = QtWidgets.QLabel(self.weather_widget)
        self.weather_act_label.setGeometry(QtCore.QRect(150, 10, 100, 75))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.weather_act_label.setFont(font)
        self.weather_act_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weather_act_label.setObjectName("weather_act_label")
        self.weather_forecast_max_label_0 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_max_label_0.setGeometry(QtCore.QRect(35, 200, 25, 16))
        self.weather_forecast_max_label_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weather_forecast_max_label_0.setObjectName("weather_forecast_max_label_0")
        self.weather_forecast_min_label_0 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_min_label_0.setGeometry(QtCore.QRect(10, 200, 25, 16))
        self.weather_forecast_min_label_0.setObjectName("weather_forecast_min_label_0")
        self.rainprobability_graphic_0 = QtWidgets.QGraphicsView(self.weather_widget)
        self.rainprobability_graphic_0.setGeometry(QtCore.QRect(10, 180, 15, 20))
        self.rainprobability_graphic_0.setObjectName("rainprobability_graphic_0")
        self.weather_forecast_day_label_0 = QtWidgets.QLabel(self.weather_widget)
        self.weather_forecast_day_label_0.setGeometry(QtCore.QRect(10, 110, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weather_forecast_day_label_0.setFont(font)
        self.weather_forecast_day_label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_forecast_day_label_0.setObjectName("weather_forecast_day_label_0")
        self.rainprobability_label_0 = QtWidgets.QLabel(self.weather_widget)
        self.rainprobability_label_0.setGeometry(QtCore.QRect(25, 180, 35, 20))
        self.rainprobability_label_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rainprobability_label_0.setObjectName("rainprobability_label_0")
        self.weather_forecast_graphic_0 = QtWidgets.QGraphicsView(self.weather_widget)
        self.weather_forecast_graphic_0.setGeometry(QtCore.QRect(10, 130, 50, 50))
        self.weather_forecast_graphic_0.setObjectName("weather_forecast_graphic_0")
        self.wind_label = QtWidgets.QLabel(self.weather_widget)
        self.wind_label.setGeometry(QtCore.QRect(30, 85, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wind_label.setFont(font)
        self.wind_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wind_label.setObjectName("wind_label")
        self.wind_graphic = QtWidgets.QGraphicsView(self.weather_widget)
        self.wind_graphic.setGeometry(QtCore.QRect(10, 85, 20, 20))
        self.wind_graphic.setObjectName("wind_graphic")
        self.clock_widget = QtWidgets.QWidget(Dialog)
        self.clock_widget.setGeometry(QtCore.QRect(10, 620, 200, 130))
        self.clock_widget.setObjectName("clock_widget")
        self.act_date_label = QtWidgets.QLabel(self.clock_widget)
        self.act_date_label.setGeometry(QtCore.QRect(20, 100, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.act_date_label.setFont(font)
        self.act_date_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.act_date_label.setObjectName("act_date_label")
        self.time_label = QtWidgets.QLabel(self.clock_widget)
        self.time_label.setGeometry(QtCore.QRect(0, 0, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName("time_label")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1080, 760))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setObjectName("graphicsView")
        self.user_button_1 = QtWidgets.QPushButton(Dialog)
        self.user_button_1.setGeometry(QtCore.QRect(860, 10, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.user_button_1.setFont(font)
        self.user_button_1.setFlat(True)
        self.user_button_1.setObjectName("user_button_1")
        self.user_button_2 = QtWidgets.QPushButton(Dialog)
        self.user_button_2.setGeometry(QtCore.QRect(970, 10, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.user_button_2.setFont(font)
        self.user_button_2.setFlat(True)
        self.user_button_2.setObjectName("user_button_2")
        self.graphicsView.raise_()
        self.calendar_widget.raise_()
        self.weather_widget.raise_()
        self.clock_widget.raise_()
        self.user_button_1.raise_()
        self.user_button_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.weather_forecast_min_label_1.setText(_translate("Dialog", "11°"))
        self.weather_forecast_max_label_1.setText(_translate("Dialog", "24°"))
        self.rainprobability_label_1.setText(_translate("Dialog", "50%"))
        self.weather_forecast_day_label_1.setText(_translate("Dialog", "So"))
        self.weather_forecast_max_label_2.setText(_translate("Dialog", "23°"))
        self.rainprobability_label_2.setText(_translate("Dialog", "30%"))
        self.weather_forecast_min_label_2.setText(_translate("Dialog", "12°"))
        self.weather_forecast_day_label_2.setText(_translate("Dialog", "Mo"))
        self.weather_forecast_day_label_3.setText(_translate("Dialog", "Di"))
        self.weather_forecast_min_label_3.setText(_translate("Dialog", "13°"))
        self.weather_forecast_max_label_3.setText(_translate("Dialog", "22°"))
        self.rainprobability_label_3.setText(_translate("Dialog", "20%"))
        self.weather_feel_label.setText(_translate("Dialog", "gefühlt: 10°"))
        self.weather_act_label.setText(_translate("Dialog", "20°"))
        self.weather_forecast_max_label_0.setText(_translate("Dialog", "25°"))
        self.weather_forecast_min_label_0.setText(_translate("Dialog", "10°"))
        self.weather_forecast_day_label_0.setText(_translate("Dialog", "heute"))
        self.rainprobability_label_0.setText(_translate("Dialog", "10%"))
        self.wind_label.setText(_translate("Dialog", "20 km/h"))
        self.act_date_label.setText(_translate("Dialog", "Samstag, 15. September"))
        self.time_label.setText(_translate("Dialog", "15:00"))
        self.user_button_1.setText(_translate("Dialog", "Tanja"))
        self.user_button_2.setText(_translate("Dialog", "Norman"))





if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()


    # beendet programm beim schließen des fensters
    sys.exit(app.exec_())

